name: Maarifa Project CI/CD to Render

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.19.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests defined, skipping"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/deploy/srv-XXXXXX \
          -H "Authorization: Bearer $RENDER_API_KEY"
